source 'https://rubygems.org'
# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.0.0', '>= 5.0.0.1'
# Use pg as the database for Active Record
gem 'pg'
# Simple, secure token based authentication for Rails.

gem 'devise'
gem 'devise_token_auth'

# Oauth2
gem 'omniauth'
gem 'omniauth-facebook'
gem 'omniauth-google-oauth2'
gem 'fb_graph2'
gem 'koala', '~> 2.2'

# Attachment
gem 'delayed_paperclip'
gem 'paperclip'

# Views engine
gem 'haml-rails'

# Search & Sort
gem 'ransack'
gem 'pg_search'

# Pagination
gem 'kaminari'
gem 'aws-sdk'

# Background running
gem 'sidekiq'
gem 'sidekiq-cron', '~> 0.4.5'

# Server config
gem 'dotenv-rails'

# Sendgrid
gem 'sendgrid-ruby'

# Geocoding
gem 'geokit'
gem 'geokit-rails'
# Bootstrap
source 'https://rails-assets.org' do
  gem 'rails-assets-bootstrap', '~> 4.0.0.alpha5'
  gem 'rails-assets-tether'
end

# Simple form
gem 'simple_form'

# Cross Origin Allow
gem 'rack-cors', :require => 'rack/cors'

# Automatic string generate
gem 'ffaker'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.2'
# See https://github.com/rails/execjs#readme for more supported runtimes
gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# JSON generation
gem 'active_model_serializers'
# Use Redis adapter to run Action Cable in production
gem 'redis', '~> 3.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Push notification
gem 'pushmeup'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development
group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platform: :mri
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'web-console'
  gem 'listen'
  gem 'puma'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'mailcatcher'
  gem 'spring'
  gem 'spring-watcher-listen'
end

group :test do
  gem 'capybara'
  gem 'simplecov'
  gem 'rspec-rails'
  gem 'factory_girl_rails'
  gem 'rails-controller-testing'
  gem 'database_cleaner'
  gem 'guard-rspec', require: false
  gem 'shoulda-matchers'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
