# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b3f6633c20363a4e3bf95149039322d8c35a87e80417610c9a7a69d8ad9db1a5e07ea8d26be8b1ce095714c3a17fb88bbe3bd8baf671959d6626f0d178ad339

test:
  secret_key_base: d8cba463efc22d696acb110ab1e4b913c29a46a2d823028933389548b6cfdda11fef1bf809776cb08a81d002b94f67289b0c87da7833686fccaa62838cbc44f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
